title: Showcase
baseurl: ""
url: "https://themintcoder.org"
email: kenneth@themintcoder.org
description: >-
  Portfolio of Kenneth, developer and designer.
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
